app:
  prefix: dev-

wms:
  oauth2:
    authorization:
      refreshTokenValidity: '864000'

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  kafka:
    producerClientId: dev-${HOSTNAME}
    consumerClientId: dev-${HOSTNAME}
    bootstrapServers: kafka-proxy-mcs-server.svc-internal-kafka-proxy:6667

