wms:
  oauth2:
    enable-authentication: true
    token-service-address: "ACCOUNT SERVICE ADDRESS"
    enable-worker-info-filter: true

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    username: "***USERNAME***"
    password: "***PASSWORD***"
    url: "***JDBC_URL***"
    hikari:
      data-source-properties: readOnlyMode=ignore

  kafka:
    bootstrap-servers: "***URLs***"
    listener:
      ack-mode: manual_immediate
      poll-timeout: 1s
    consumer:
      group-id: "***GROUP_ID***"
      enable-auto-commit: false
      auto-offset-reset: earliest
      properties:
        spring:
          json:
            trusted:
              packages: "*"
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      key-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      client-id: "***CLIENT_ID***"
      retries: 3
      properties:
        linger:
          ms: 1_000
        max:
          block:
            ms: 5_000
        request:
          timeout:
            ms: 30_000
        reconnect:
          backoff:
            max:
              ms: 5_000
  liquibase:
    enabled: true
    default-schema: public
    change-log: classpath:/db/changelog-master.xml


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,mappings
