apiVersion: v1
kind: Secret
metadata:
  name: {{ include "server.name" . | quote }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
  annotations:
    {{- include "server.annotations" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: {{ .Values.server.postgres.user | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.server.postgres.password | quote }}
  {{- if and .Values.server.config.spring.kafka.security.saslProperties.jaasConfig 
    (and .Values.server.config.spring.kafka.user .Values.server.config.spring.kafka.password) 
  }}
  SPRING_KAFKA_CONSUMER_PROPERTIES_SASL_JAAS_CONFIG: {{ .Values.server.config.spring.kafka.security.saslProperties.jaasConfig | replace "%username%" .Values.server.config.spring.kafka.user | replace  "%password%" .Values.server.config.spring.kafka.password | quote }}
  SPRING_KAFKA_PRODUCER_PROPERTIES_SASL_JAAS_CONFIG: {{ .Values.server.config.spring.kafka.security.saslProperties.jaasConfig | replace "%username%" .Values.server.config.spring.kafka.user | replace  "%password%" .Values.server.config.spring.kafka.password | quote }}
  {{- end }}
