apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "server.name" . | quote }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.server.tracing.jaeger.injectAgent }}
    sidecar.jaegertracing.io/inject: "true"
    {{- end }}
    {{- include "server.annotations" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "server.selector" . | nindent 6 }}
  replicas: {{ .Values.server.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        {{- include "server.labels" . | nindent 8 }}
        {{- include "quote.object" .Values.server.pods.labels | indent 8}}
      annotations:
        {{- include "server.annotations" . | nindent 8 }}
    spec:
      {{- if .Values.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.pullSecret }}
      {{- end }}
      containers:
        - name: server
          image: {{ .Values.server.image | quote }}
          imagePullPolicy: {{ .Values.pullPolicy | quote }}
          resources: {{- toYaml .Values.server.resources | nindent 14 }}
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: KUBE_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KUBE_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - configMapRef:
                name: {{ include "server.name" . | quote }}
            - secretRef:
                name: {{ include "server.name" . | quote }}
          ports:
            - name: "api"
              containerPort: {{ .Values.server.api.port.internal }}
              protocol: TCP
          {{- if .Values.server.probes.readiness }}
          readinessProbe: {{- toYaml .Values.server.probes.readiness | nindent 12 }}
          {{- end }}
          {{- if .Values.server.probes.liveness }}
          livenessProbe: {{- toYaml .Values.server.probes.liveness | nindent 12 }}
          {{- end }}

      {{- if .Values.server.nodeSelector }}
      nodeSelector: {{ toYaml .Values.server.nodeSelector | nindent 8 }}
      {{- end }}

      {{- if .Values.server.affinity }}
      affinity: {{ toYaml .Values.server.affinity | nindent 8 }}
      {{- end }}

      {{- if .Values.server.tolerations }}
      tolerations: {{ toYaml .Values.server.tolerations | nindent 8 }}
      {{- end }}
