server:
  replicas: 1

  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 600m
      memory: 768Mi

  postgres:
    host: wms-db.master.dev.um.internal

  config:
    # xmx must be lower than memory limit by 10-20%
    javaOpts: -Xmx600m
    spring:
      app:
        prefix: dev-
      kafka:
        producerClientId: dev-${HOSTNAME}
        consumerClientId: dev-${HOSTNAME}
        bootstrapServers: common-kafka.dev.um.internal:9092
      sleuth:
        samplerProbability: 1
    kazanexpress:
      kafka:
        suffix: _test
    wms:
      oauth2:
        enableAuthentication: true
        tokenServiceAddress: http://wms-account
        authorization:
          accessTokenValidity: '86400'
          refreshTokenValidity: '864000'

  ingress:
    annotations:
      nginx.ingress.kubernetes.io/affinity: cookie
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/rewrite-target: /$1
      nginx.ingress.kubernetes.io/session-cookie-name: route
    tls:
      - hosts:
          - api.wms.dev.cluster.daymarket.uz
        secretName: wms-api-metaship-ssl
    rules:
      - host: api.wms.dev.cluster.daymarket.uz
        paths:
          - path: /metaship/(.*)
            pathType: ImplementationSpecific
            port: 80
